WINDOW_SETTINGS = (1000, 700)
HORIZONT = 380

BULLET_WIDTH = 5
BULLET_HEIGHT = 20

GUN_WIDTH = 130
GUN_HEIGHT = 50

SPEED = 1
BULLET_SPEED = 100

FONT_NAME_MENU = "Comic Sans MS"
FONT_SIZE_MENU = 50

FONT_NAME_GAME = "Comic Sans MS"
FONT_SIZE_GAME = 30

FONT_NAME_RECORDS = "Comic Sans MS"
FONT_SIZE_RECORDS = 35

FONT_NAME_SHOP = "Comic Sans MS"
FONT_SIZE_SHOP = 30

COLOR_MENU = (0, 0, 0)
COLOR_MENU_ACTIVE = (0, 255, 0)

COLOR_GAME_BACKGROUND = (207, 143, 17)

SPEED_ELEPHANT, POINTS_ELEPHANT, LIVES_ELEPHANT = -1, 2, 3
SPEED_LION, POINTS_LION, LIVES_LION = 4, 10, 2
SPEED_TIGER, POINTS_TIGER, LIVES_TIGER = -5, 15, 2
SPEED_JERBOA, POINTS_JERBOA, LIVES_JERBOA = 2, 20, 1  # ТУШКАНЧИК
SPEED_OSTRICH, POINTS_OSTRICH, LIVES_OSTRICH = -3, 7, 2  # СТРАУС
SPEED_HYENA, POINTS_HYENA, LIVES_HYENA = -3, 8, 2
SPEED_HAWK, POINTS_HAWK, LIVES_HAWK = 1, 2, 1  # ЯСТРЕБ
SPEED_ZEBRA, POINTS_ZEBRA, LIVES_ZEBRA = -2, 3, 1
SPEED_IRONCLAD, POINTS_IRONCLAD, LIVES_IRONCLAD = -2, 1, 5  # БРОНЕНОСЕЦ !!!!!!!!!!!!
SPEED_ECHIDNA, POINTS_ECHIDNA, LIVES_ECHIDNA = -3, 16, 1  # МЕЛКИЙ АФРИКАНСКИЙ ЕЖ !!!!!!!
SPEED_CHAMELEON, POINTS_CHAMELEON, LIVES_CHAMELEON = 1, 20, 1

